# Exercise 1 - Numpy

In [2]:
import numpy as np

## task 1

In [5]:
mat1 = np.ones((3, 4))
mat2 = np.zeros((3, 2))

In [12]:
np.hstack((mat1, mat2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## task 2

In [16]:
M = np.arange(30).reshape((5, 6))
a = np.array([2, 4, 0, 3, 2])
b = np.array([1, 0, 5, 3, 4])

In [21]:
print(M)
print("Answer:")
print(M[a, b])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Answer:
[13 24  5 21 16]


## task 3

In [23]:
M = np.arange(25).reshape((5, 5))

In [27]:
print(M)
print("Trace = ", np.trace(M))
print("Count of nonzero elements = ", np.count_nonzero(np.diag(M)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Trace =  60
Count of nonzero elements =  4


## task 4

In [34]:
rg = np.random.default_rng(1)
T = np.floor(10 * rg.random((3, 4, 5, 5))).astype(int)

In [36]:
np.unique(T, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([31, 33, 32, 31, 26, 26, 34, 31, 28, 28], dtype=int64))

## task 5

In [39]:
First = np.floor(10 * rg.random((4, 6)) - 5)
Second = np.floor(10 * rg.random((4, 6)) - 5)

In [41]:
print(First)
Second[First<0] = 0
print(Second)

[[-3. -2.  0. -1. -4.  4.]
 [ 1.  3. -2.  4.  3.  4.]
 [-4. -1. -2.  1. -3. -4.]
 [-1.  1. -2.  4. -1. -3.]]
[[ 0.  0. -3.  0.  0.  4.]
 [ 1. -3.  0. -3. -2.  0.]
 [ 0.  0.  0. -4.  0.  0.]
 [ 0. -3.  0.  2.  0.  0.]]
